package api

import (
	"context"
	"database/sql"
	"encoding/csv"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"mime/multipart"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"

	"pms/backend/internal/permissions"
	"pms/backend/internal/store"
)

type financeCategoryRow struct {
	ID                         int64  `json:"id"`
	PropertyID                 *int64 `json:"property_id"`
	Code                       string `json:"code"`
	Title                      string `json:"title"`
	Direction                  string `json:"direction"`
	CountsTowardPropertyIncome bool   `json:"counts_toward_property_income"`
	Active                     bool   `json:"active"`
	CreatedAt                  string `json:"created_at"`
	UpdatedAt                  string `json:"updated_at"`
}

type financeCategoriesResponse struct {
	Categories []financeCategoryRow `json:"categories"`
}

type financeTransactionRow struct {
	ID              int64   `json:"id"`
	TransactionDate string  `json:"transaction_date"`
	Direction       string  `json:"direction"`
	AmountCents     int     `json:"amount_cents"`
	CategoryID      *int64  `json:"category_id"`
	CategoryCode    *string `json:"category_code"`
	CategoryTitle   *string `json:"category_title"`
	Note            *string `json:"note"`
	SourceType      string  `json:"source_type"`
	SourceReference *string `json:"source_reference_id"`
	IsAutoGenerated bool    `json:"is_auto_generated"`
	AttachmentPath  *string `json:"attachment_path"`
	MappedToStay    bool    `json:"mapped_to_stay"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

type financeTransactionsResponse struct {
	Month        string                  `json:"month"`
	Transactions []financeTransactionRow `json:"transactions"`
}

type financeBookingPayoutRow struct {
	ID                     int64   `json:"id"`
	ReferenceNumber        string  `json:"reference_number"`
	PayoutID               *string `json:"payout_id"`
	RowType                *string `json:"row_type"`
	CheckInDate            *string `json:"check_in_date"`
	CheckOutDate           *string `json:"check_out_date"`
	GuestName              *string `json:"guest_name"`
	HostName               *string `json:"host_name"`
	PayoutSummary          *string `json:"payout_summary"`
	ReservationStatus      *string `json:"reservation_status"`
	Currency               *string `json:"currency"`
	PaymentStatus          *string `json:"payment_status"`
	AmountCents            *int64  `json:"amount_cents"`
	CommissionCents        *int64  `json:"commission_cents"`
	PaymentServiceFeeCents *int64  `json:"payment_service_fee_cents"`
	NetCents               int     `json:"net_cents"`
	PayoutDate             string  `json:"payout_date"`
	TransactionID          *int64  `json:"transaction_id"`
	OccupancyID            *int64  `json:"occupancy_id"`
	OccupancyStartAt       *string `json:"occupancy_start_at"`
	OccupancyEndAt         *string `json:"occupancy_end_at"`
	OccupancySummary       *string `json:"occupancy_summary"`
	LinkedInvoiceID        *int64  `json:"linked_invoice_id"`
}

type financeBookingPayoutsResponse struct {
	Month      string                    `json:"month"`
	MappedOnly string                    `json:"mapped_only"`
	Payouts    []financeBookingPayoutRow `json:"payouts"`
}

type financeRecurringRuleRow struct {
	ID            int64   `json:"id"`
	Title         string  `json:"title"`
	CategoryID    *int64  `json:"category_id"`
	AmountCents   int     `json:"amount_cents"`
	Direction     string  `json:"direction"`
	Frequency     string  `json:"frequency"`
	StartMonth    string  `json:"start_month"`
	EndMonth      *string `json:"end_month"`
	EffectiveFrom string  `json:"effective_from"`
	EffectiveTo   *string `json:"effective_to"`
	Active        bool    `json:"active"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

type financeRecurringRulesResponse struct {
	Rules []financeRecurringRuleRow `json:"rules"`
}

type financeSummaryBreakdownRow struct {
	CategoryID    *int64  `json:"category_id"`
	CategoryCode  *string `json:"category_code"`
	CategoryTitle *string `json:"category_title"`
	IncomingCents int     `json:"incoming_cents"`
	OutgoingCents int     `json:"outgoing_cents"`
}

type financeSummaryResponse struct {
	Month                      string                       `json:"month"`
	TotalIncomingCents         int                          `json:"total_incoming_cents"`
	TotalOutgoingCents         int                          `json:"total_outgoing_cents"`
	MonthlyIncomingCents       int                          `json:"monthly_incoming_cents"`
	MonthlyOutgoingCents       int                          `json:"monthly_outgoing_cents"`
	MonthlyNetCents            int                          `json:"monthly_net_cents"`
	PropertyIncomeCents        int                          `json:"property_income_cents"`
	MonthlyPropertyIncomeCents int                          `json:"monthly_property_income_cents"`
	CleanerExpenseCents        int                          `json:"cleaner_expense_cents"`
	CleanerMargin              float64                      `json:"cleaner_margin"`
	Breakdown                  []financeSummaryBreakdownRow `json:"breakdown"`
}

func categoryToRow(c store.FinanceCategory) financeCategoryRow {
	return financeCategoryRow{
		ID:                         c.ID,
		PropertyID:                 nullInt64Ptr(c.PropertyID),
		Code:                       c.Code,
		Title:                      c.Title,
		Direction:                  c.Direction,
		CountsTowardPropertyIncome: c.CountsTowardPropertyIncome,
		Active:                     c.Active,
		CreatedAt:                  c.CreatedAt.UTC().Format(time.RFC3339),
		UpdatedAt:                  c.UpdatedAt.UTC().Format(time.RFC3339),
	}
}

func txToRow(t store.FinanceTransaction) financeTransactionRow {
	return financeTransactionRow{
		ID:              t.ID,
		TransactionDate: t.TransactionDate.UTC().Format(time.RFC3339),
		Direction:       t.Direction,
		AmountCents:     t.AmountCents,
		CategoryID:      nullInt64Ptr(t.CategoryID),
		CategoryCode:    nullStringPtr(t.CategoryCode),
		CategoryTitle:   nullStringPtr(t.CategoryTitle),
		Note:            nullStringPtr(t.Note),
		SourceType:      t.SourceType,
		SourceReference: nullStringPtr(t.SourceReference),
		IsAutoGenerated: t.IsAutoGenerated,
		AttachmentPath:  nullStringPtr(t.AttachmentPath),
		MappedToStay:    t.MappedToStay,
		CreatedAt:       t.CreatedAt.UTC().Format(time.RFC3339),
		UpdatedAt:       t.UpdatedAt.UTC().Format(time.RFC3339),
	}
}

func recurringToRow(r store.FinanceRecurringRule) financeRecurringRuleRow {
	return financeRecurringRuleRow{
		ID:            r.ID,
		Title:         r.Title,
		CategoryID:    nullInt64Ptr(r.CategoryID),
		AmountCents:   r.AmountCents,
		Direction:     r.Direction,
		Frequency:     r.Frequency,
		StartMonth:    r.StartMonth,
		EndMonth:      nullStringPtr(r.EndMonth),
		EffectiveFrom: r.EffectiveFrom.UTC().Format(time.RFC3339),
		EffectiveTo:   nullTimePtr(r.EffectiveTo),
		Active:        r.Active,
		CreatedAt:     r.CreatedAt.UTC().Format(time.RFC3339),
		UpdatedAt:     r.UpdatedAt.UTC().Format(time.RFC3339),
	}
}

func (s *Server) listFinanceCategories(w http.ResponseWriter, r *http.Request) {
	_, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelRead)
	if !ok {
		return
	}
	rows, err := s.Store.ListFinanceCategories(r.Context(), pid)
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "database error")
		return
	}
	out := make([]financeCategoryRow, 0, len(rows))
	for _, c := range rows {
		out = append(out, categoryToRow(c))
	}
	WriteJSON(w, http.StatusOK, financeCategoriesResponse{Categories: out})
}

func (s *Server) postFinanceCategory(w http.ResponseWriter, r *http.Request) {
	actor, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelWrite)
	if !ok {
		return
	}
	var body struct {
		Code                       string `json:"code"`
		Title                      string `json:"title"`
		Direction                  string `json:"direction"`
		CountsTowardPropertyIncome bool   `json:"counts_toward_property_income"`
	}
	if err := ReadJSON(r, &body); err != nil {
		WriteError(w, http.StatusBadRequest, "invalid json")
		return
	}
	body.Code = strings.TrimSpace(strings.ToLower(body.Code))
	body.Title = strings.TrimSpace(body.Title)
	if body.Code == "" || body.Title == "" {
		WriteError(w, http.StatusBadRequest, "code and title are required")
		return
	}
	switch body.Direction {
	case "incoming", "outgoing", "both":
	default:
		WriteError(w, http.StatusBadRequest, "direction must be incoming, outgoing, or both")
		return
	}
	row, err := s.Store.CreateFinanceCategory(r.Context(), pid, body.Code, body.Title, body.Direction, body.CountsTowardPropertyIncome)
	if err != nil {
		WriteError(w, http.StatusConflict, "category already exists")
		return
	}
	s.audit(r, actor, "finance_category_create", "property", strconv.FormatInt(pid, 10), "success")
	WriteJSON(w, http.StatusCreated, map[string]interface{}{"category": categoryToRow(*row)})
}

func (s *Server) listFinanceTransactions(w http.ResponseWriter, r *http.Request) {
	_, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelRead)
	if !ok {
		return
	}
	month := strings.TrimSpace(r.URL.Query().Get("month"))
	if month != "" {
		if _, _, err := parseFinanceMonth(month); err != nil {
			WriteError(w, http.StatusBadRequest, "month must be YYYY-MM")
			return
		}
	}
	rows, err := s.Store.ListFinanceTransactions(r.Context(), pid, month, 0, 0)
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "database error")
		return
	}
	out := make([]financeTransactionRow, 0, len(rows))
	for _, t := range rows {
		out = append(out, txToRow(t))
	}
	WriteJSON(w, http.StatusOK, financeTransactionsResponse{Month: month, Transactions: out})
}

func (s *Server) listFinanceBookingPayouts(w http.ResponseWriter, r *http.Request) {
	_, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelRead)
	if !ok {
		return
	}
	propName := ""
	if p, err := s.Store.GetProperty(r.Context(), pid); err == nil {
		propName = strings.TrimSpace(p.Name)
	}
	month := strings.TrimSpace(r.URL.Query().Get("month"))
	if month != "" {
		if _, _, err := parseFinanceMonth(month); err != nil {
			WriteError(w, http.StatusBadRequest, "month must be YYYY-MM")
			return
		}
	}
	mappedOnlyRaw := strings.TrimSpace(strings.ToLower(r.URL.Query().Get("mapped_only")))
	var mappedOnly *bool
	if mappedOnlyRaw == "1" || mappedOnlyRaw == "true" || mappedOnlyRaw == "yes" {
		v := true
		mappedOnly = &v
	} else if mappedOnlyRaw == "0" || mappedOnlyRaw == "false" || mappedOnlyRaw == "no" {
		v := false
		mappedOnly = &v
	}
	rows, err := s.Store.ListBookingPayouts(r.Context(), pid, month, mappedOnly)
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "database error")
		return
	}
	out := make([]financeBookingPayoutRow, 0, len(rows))
	for _, rr := range rows {
		out = append(out, financeBookingPayoutRow{
			ID:                     rr.ID,
			ReferenceNumber:        rr.ReferenceNumber,
			PayoutID:               nullStringPtr(rr.PayoutID),
			RowType:                nullStringPtr(rr.RowType),
			CheckInDate:            nullStringPtr(rr.CheckInDate),
			CheckOutDate:           nullStringPtr(rr.CheckOutDate),
			GuestName:              fixCSVMojibakePtr(nullStringPtr(rr.GuestName)),
			HostName:               bookingPayoutHostName(rr.RawRowJSON),
			PayoutSummary:          financeBookingPayoutSummary(rr.RawRowJSON, rr.GuestName, rr.OccupancySummary, propName),
			ReservationStatus:      nullStringPtr(rr.ReservationStatus),
			Currency:               nullStringPtr(rr.Currency),
			PaymentStatus:          nullStringPtr(rr.PaymentStatus),
			AmountCents:            nullInt64Ptr(rr.AmountCents),
			CommissionCents:        nullInt64Ptr(rr.CommissionCents),
			PaymentServiceFeeCents: nullInt64Ptr(rr.PaymentServiceFeeCents),
			NetCents:               rr.NetCents,
			PayoutDate:             rr.PayoutDate.UTC().Format(time.RFC3339),
			TransactionID:          nullInt64Ptr(rr.TransactionID),
			OccupancyID:            nullInt64Ptr(rr.OccupancyID),
			OccupancyStartAt:       nullTimePtr(rr.OccupancyStartAt),
			OccupancyEndAt:         nullTimePtr(rr.OccupancyEndAt),
			OccupancySummary:       fixCSVMojibakePtr(nullStringPtr(rr.OccupancySummary)),
			LinkedInvoiceID:        nullInt64Ptr(rr.LinkedInvoiceID),
		})
	}
	WriteJSON(w, http.StatusOK, financeBookingPayoutsResponse{Month: month, MappedOnly: mappedOnlyRaw, Payouts: out})
}

func (s *Server) postFinanceTransaction(w http.ResponseWriter, r *http.Request) {
	actor, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelWrite)
	if !ok {
		return
	}
	if s.AttachmentUploadLimiter != nil {
		if !s.AttachmentUploadLimiter.Allow(fmt.Sprintf("attachment_upload:%d", actor.ID)) {
			w.Header().Set("Retry-After", "2")
			WriteError(w, http.StatusTooManyRequests, "too many attachment uploads")
			return
		}
	}
	prop, err := s.Store.GetProperty(r.Context(), pid)
	if err != nil {
		WriteError(w, http.StatusNotFound, "property not found")
		return
	}
	loc, err := time.LoadLocation(prop.Timezone)
	if err != nil {
		loc = time.UTC
	}
	row, pending, err := s.parseTransactionCreateRequest(r, pid, loc)
	if err != nil {
		WriteError(w, http.StatusBadRequest, err.Error())
		return
	}
	if pending != nil {
		defer pending.Close()
	}
	created, err := s.Store.CreateFinanceTransaction(r.Context(), row)
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "create failed")
		return
	}
	if pending != nil {
		path, saveErr := s.saveFinanceAttachment(pid, created.ID, pending.header, pending.file)
		if saveErr != nil {
			WriteError(w, http.StatusBadRequest, saveErr.Error())
			return
		}
		if path != "" {
			updated, updErr := s.Store.UpdateFinanceTransaction(r.Context(), pid, created.ID, nil, nil, nil, nil, nil, &path)
			if updErr != nil {
				WriteError(w, http.StatusInternalServerError, "attachment link failed")
				return
			}
			created = updated
		}
	}
	s.audit(r, actor, "finance_transaction_create", "finance_transaction", strconv.FormatInt(created.ID, 10), "success")
	WriteJSON(w, http.StatusCreated, map[string]interface{}{"transaction": txToRow(*created)})
}

func (s *Server) patchFinanceTransaction(w http.ResponseWriter, r *http.Request) {
	actor, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelWrite)
	if !ok {
		return
	}
	tid, err := strconv.ParseInt(chi.URLParam(r, "transactionId"), 10, 64)
	if err != nil {
		WriteError(w, http.StatusBadRequest, "invalid transaction id")
		return
	}
	prop, err := s.Store.GetProperty(r.Context(), pid)
	if err != nil {
		WriteError(w, http.StatusNotFound, "property not found")
		return
	}
	loc, err := time.LoadLocation(prop.Timezone)
	if err != nil {
		loc = time.UTC
	}
	var body struct {
		TransactionDate *string `json:"transaction_date"`
		Direction       *string `json:"direction"`
		AmountCents     *int    `json:"amount_cents"`
		CategoryID      *int64  `json:"category_id"`
		Note            *string `json:"note"`
	}
	if err := ReadJSON(r, &body); err != nil {
		WriteError(w, http.StatusBadRequest, "invalid json")
		return
	}
	var txDate *time.Time
	if body.TransactionDate != nil {
		t, err := parseFinanceDate(strings.TrimSpace(*body.TransactionDate), loc)
		if err != nil {
			WriteError(w, http.StatusBadRequest, "transaction_date must be RFC3339 or YYYY-MM-DD")
			return
		}
		txDate = &t
	}
	if body.Direction != nil {
		d := strings.TrimSpace(*body.Direction)
		if d != "incoming" && d != "outgoing" {
			WriteError(w, http.StatusBadRequest, "direction must be incoming or outgoing")
			return
		}
		body.Direction = &d
	}
	if body.AmountCents != nil && *body.AmountCents < 0 {
		WriteError(w, http.StatusBadRequest, "amount_cents must be >= 0")
		return
	}
	if body.CategoryID != nil && *body.CategoryID > 0 {
		if _, err := s.Store.GetFinanceCategoryByID(r.Context(), pid, *body.CategoryID); err != nil {
			WriteError(w, http.StatusBadRequest, "invalid category_id")
			return
		}
	}
	updated, err := s.Store.UpdateFinanceTransaction(r.Context(), pid, tid, txDate, body.Direction, body.AmountCents, body.CategoryID, body.Note, nil)
	if err != nil {
		if strings.Contains(err.Error(), "read_only") {
			WriteError(w, http.StatusBadRequest, "auto-generated transactions cannot be edited")
			return
		}
		if errors.Is(err, sql.ErrNoRows) {
			WriteError(w, http.StatusNotFound, "transaction not found")
			return
		}
		WriteError(w, http.StatusInternalServerError, "update failed")
		return
	}
	s.audit(r, actor, "finance_transaction_update", "finance_transaction", strconv.FormatInt(updated.ID, 10), "success")
	WriteJSON(w, http.StatusOK, map[string]interface{}{"transaction": txToRow(*updated)})
}

func (s *Server) deleteFinanceTransaction(w http.ResponseWriter, r *http.Request) {
	actor, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelWrite)
	if !ok {
		return
	}
	tid, err := strconv.ParseInt(chi.URLParam(r, "transactionId"), 10, 64)
	if err != nil {
		WriteError(w, http.StatusBadRequest, "invalid transaction id")
		return
	}
	if err := s.Store.DeleteFinanceTransaction(r.Context(), pid, tid); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			WriteError(w, http.StatusNotFound, "transaction not found")
			return
		}
		WriteError(w, http.StatusInternalServerError, "delete failed")
		return
	}
	s.audit(r, actor, "finance_transaction_delete", "finance_transaction", strconv.FormatInt(tid, 10), "success")
	w.WriteHeader(http.StatusNoContent)
}

func (s *Server) openFinanceMonth(w http.ResponseWriter, r *http.Request) {
	actor, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelWrite)
	if !ok {
		return
	}
	month := strings.TrimSpace(chi.URLParam(r, "month"))
	if _, _, err := parseFinanceMonth(month); err != nil {
		WriteError(w, http.StatusBadRequest, "month must be YYYY-MM")
		return
	}
	prop, err := s.Store.GetProperty(r.Context(), pid)
	if err != nil {
		WriteError(w, http.StatusNotFound, "property not found")
		return
	}
	loc, err := time.LoadLocation(prop.Timezone)
	if err != nil {
		loc = time.UTC
	}
	var by *int64
	if actor != nil {
		by = &actor.ID
	}
	n, err := s.Store.OpenFinanceMonth(r.Context(), pid, month, by, loc)
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "open month failed")
		return
	}
	s.audit(r, actor, "finance_month_open", "property", strconv.FormatInt(pid, 10), "success")
	WriteJSON(w, http.StatusOK, map[string]interface{}{"ok": true, "generated_recurring_count": n})
}

func (s *Server) getFinanceSummary(w http.ResponseWriter, r *http.Request) {
	_, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelRead)
	if !ok {
		return
	}
	prop, err := s.Store.GetProperty(r.Context(), pid)
	if err != nil {
		WriteError(w, http.StatusNotFound, "property not found")
		return
	}
	loc, err := time.LoadLocation(prop.Timezone)
	if err != nil {
		loc = time.UTC
	}
	month, _, _ := s.parseMonthInPropertyTZ(r, loc)
	if month == "" {
		WriteError(w, http.StatusBadRequest, "month must be YYYY-MM")
		return
	}
	sum, err := s.Store.ComputeFinanceSummary(r.Context(), pid, month)
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "database error")
		return
	}
	breakdown := make([]financeSummaryBreakdownRow, 0, len(sum.Breakdown))
	for _, b := range sum.Breakdown {
		breakdown = append(breakdown, financeSummaryBreakdownRow{
			CategoryID:    nullInt64Ptr(b.CategoryID),
			CategoryCode:  nullStringPtr(b.CategoryCode),
			CategoryTitle: nullStringPtr(b.CategoryTitle),
			IncomingCents: b.IncomingCents,
			OutgoingCents: b.OutgoingCents,
		})
	}
	WriteJSON(w, http.StatusOK, financeSummaryResponse{
		Month:                      month,
		TotalIncomingCents:         sum.TotalIncomingCents,
		TotalOutgoingCents:         sum.TotalOutgoingCents,
		MonthlyIncomingCents:       sum.MonthlyIncomingCents,
		MonthlyOutgoingCents:       sum.MonthlyOutgoingCents,
		MonthlyNetCents:            sum.MonthlyNetCents,
		PropertyIncomeCents:        sum.PropertyIncomeCents,
		MonthlyPropertyIncomeCents: sum.MonthlyPropertyIncomeCents,
		CleanerExpenseCents:        sum.CleanerExpenseCents,
		CleanerMargin:              sum.CleanerMargin,
		Breakdown:                  breakdown,
	})
}

func (s *Server) listFinanceRecurringRules(w http.ResponseWriter, r *http.Request) {
	_, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelRead)
	if !ok {
		return
	}
	rows, err := s.Store.ListFinanceRecurringRules(r.Context(), pid)
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "database error")
		return
	}
	out := make([]financeRecurringRuleRow, 0, len(rows))
	for _, rr := range rows {
		out = append(out, recurringToRow(rr))
	}
	WriteJSON(w, http.StatusOK, financeRecurringRulesResponse{Rules: out})
}

func (s *Server) postFinanceRecurringRule(w http.ResponseWriter, r *http.Request) {
	actor, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelWrite)
	if !ok {
		return
	}
	var body struct {
		Title         string  `json:"title"`
		CategoryID    *int64  `json:"category_id"`
		AmountCents   int     `json:"amount_cents"`
		Direction     string  `json:"direction"`
		StartMonth    string  `json:"start_month"`
		EndMonth      *string `json:"end_month"`
		EffectiveFrom string  `json:"effective_from"`
		EffectiveTo   *string `json:"effective_to"`
		Active        *bool   `json:"active"`
	}
	if err := ReadJSON(r, &body); err != nil {
		WriteError(w, http.StatusBadRequest, "invalid json")
		return
	}
	body.Title = strings.TrimSpace(body.Title)
	if body.Title == "" {
		WriteError(w, http.StatusBadRequest, "title is required")
		return
	}
	if body.AmountCents < 0 {
		WriteError(w, http.StatusBadRequest, "amount_cents must be >= 0")
		return
	}
	if body.Direction != "incoming" && body.Direction != "outgoing" {
		WriteError(w, http.StatusBadRequest, "direction must be incoming or outgoing")
		return
	}
	if _, _, err := parseFinanceMonth(strings.TrimSpace(body.StartMonth)); err != nil {
		WriteError(w, http.StatusBadRequest, "start_month must be YYYY-MM")
		return
	}
	if body.EndMonth != nil && strings.TrimSpace(*body.EndMonth) != "" {
		if _, _, err := parseFinanceMonth(strings.TrimSpace(*body.EndMonth)); err != nil {
			WriteError(w, http.StatusBadRequest, "end_month must be YYYY-MM")
			return
		}
	}
	effFrom, err := time.Parse(time.RFC3339, strings.TrimSpace(body.EffectiveFrom))
	if err != nil {
		WriteError(w, http.StatusBadRequest, "effective_from must be RFC3339")
		return
	}
	var effTo sql.NullTime
	if body.EffectiveTo != nil && strings.TrimSpace(*body.EffectiveTo) != "" {
		t, err := time.Parse(time.RFC3339, strings.TrimSpace(*body.EffectiveTo))
		if err != nil {
			WriteError(w, http.StatusBadRequest, "effective_to must be RFC3339")
			return
		}
		effTo = sql.NullTime{Time: t, Valid: true}
	}
	var cat sql.NullInt64
	if body.CategoryID != nil && *body.CategoryID > 0 {
		if _, err := s.Store.GetFinanceCategoryByID(r.Context(), pid, *body.CategoryID); err != nil {
			WriteError(w, http.StatusBadRequest, "invalid category_id")
			return
		}
		cat = sql.NullInt64{Int64: *body.CategoryID, Valid: true}
	}
	active := true
	if body.Active != nil {
		active = *body.Active
	}
	row, err := s.Store.CreateFinanceRecurringRule(r.Context(), &store.FinanceRecurringRule{
		PropertyID:    pid,
		Title:         body.Title,
		CategoryID:    cat,
		AmountCents:   body.AmountCents,
		Direction:     body.Direction,
		Frequency:     "monthly",
		StartMonth:    strings.TrimSpace(body.StartMonth),
		EndMonth:      sql.NullString{String: strings.TrimSpace(ptrString(body.EndMonth)), Valid: body.EndMonth != nil && strings.TrimSpace(*body.EndMonth) != ""},
		EffectiveFrom: effFrom,
		EffectiveTo:   effTo,
		Active:        active,
	})
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "create failed")
		return
	}
	s.audit(r, actor, "finance_recurring_rule_create", "finance_recurring_rule", strconv.FormatInt(row.ID, 10), "success")
	WriteJSON(w, http.StatusCreated, map[string]interface{}{"rule": recurringToRow(*row)})
}

func (s *Server) patchFinanceRecurringRule(w http.ResponseWriter, r *http.Request) {
	actor, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelWrite)
	if !ok {
		return
	}
	rid, err := strconv.ParseInt(chi.URLParam(r, "ruleId"), 10, 64)
	if err != nil {
		WriteError(w, http.StatusBadRequest, "invalid rule id")
		return
	}
	var body struct {
		Title         *string `json:"title"`
		CategoryID    *int64  `json:"category_id"`
		AmountCents   *int    `json:"amount_cents"`
		Direction     *string `json:"direction"`
		StartMonth    *string `json:"start_month"`
		EndMonth      *string `json:"end_month"`
		EffectiveFrom *string `json:"effective_from"`
		EffectiveTo   *string `json:"effective_to"`
		Active        *bool   `json:"active"`
	}
	if err := ReadJSON(r, &body); err != nil {
		WriteError(w, http.StatusBadRequest, "invalid json")
		return
	}
	if body.AmountCents != nil && *body.AmountCents < 0 {
		WriteError(w, http.StatusBadRequest, "amount_cents must be >= 0")
		return
	}
	if body.Direction != nil {
		d := strings.TrimSpace(*body.Direction)
		if d != "incoming" && d != "outgoing" {
			WriteError(w, http.StatusBadRequest, "direction must be incoming or outgoing")
			return
		}
		body.Direction = &d
	}
	if body.StartMonth != nil {
		m := strings.TrimSpace(*body.StartMonth)
		if _, _, err := parseFinanceMonth(m); err != nil {
			WriteError(w, http.StatusBadRequest, "start_month must be YYYY-MM")
			return
		}
		body.StartMonth = &m
	}
	if body.EndMonth != nil && strings.TrimSpace(*body.EndMonth) != "" {
		m := strings.TrimSpace(*body.EndMonth)
		if _, _, err := parseFinanceMonth(m); err != nil {
			WriteError(w, http.StatusBadRequest, "end_month must be YYYY-MM")
			return
		}
		body.EndMonth = &m
	}
	if body.CategoryID != nil && *body.CategoryID > 0 {
		if _, err := s.Store.GetFinanceCategoryByID(r.Context(), pid, *body.CategoryID); err != nil {
			WriteError(w, http.StatusBadRequest, "invalid category_id")
			return
		}
	}
	var effFrom *time.Time
	if body.EffectiveFrom != nil {
		t, err := time.Parse(time.RFC3339, strings.TrimSpace(*body.EffectiveFrom))
		if err != nil {
			WriteError(w, http.StatusBadRequest, "effective_from must be RFC3339")
			return
		}
		effFrom = &t
	}
	var effTo *time.Time
	if body.EffectiveTo != nil && strings.TrimSpace(*body.EffectiveTo) != "" {
		t, err := time.Parse(time.RFC3339, strings.TrimSpace(*body.EffectiveTo))
		if err != nil {
			WriteError(w, http.StatusBadRequest, "effective_to must be RFC3339")
			return
		}
		effTo = &t
	}
	row, err := s.Store.UpdateFinanceRecurringRule(r.Context(), pid, rid, body.Title, body.CategoryID, body.AmountCents, body.Direction, body.StartMonth, body.EndMonth, effFrom, effTo, body.Active)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			WriteError(w, http.StatusNotFound, "rule not found")
			return
		}
		WriteError(w, http.StatusInternalServerError, "update failed")
		return
	}
	s.audit(r, actor, "finance_recurring_rule_update", "finance_recurring_rule", strconv.FormatInt(row.ID, 10), "success")
	WriteJSON(w, http.StatusOK, map[string]interface{}{"rule": recurringToRow(*row)})
}

type bookingPayoutCSVRow struct {
	ReferenceNumber   string
	RowType           string
	CheckInDate       string
	CheckOutDate      string
	GuestName         string
	ReservationStatus string
	Currency          string
	PaymentStatus     string
	AmountCents       int
	CommissionCents   int
	PaymentFeeCents   int
	NetCents          int
	PayoutDate        time.Time
	PayoutID          string
	RawJSON           string
}

type bookingPayoutImportResponse struct {
	OK         bool     `json:"ok"`
	Imported   int      `json:"imported"`
	Duplicates int      `json:"duplicates"`
	Mapped     int      `json:"mapped"`
	Failed     int      `json:"failed"`
	Warnings   []string `json:"warnings,omitempty"`
}

type bookingPayoutRematchResponse struct {
	OK            bool `json:"ok"`
	Scanned       int  `json:"scanned"`
	Matched       int  `json:"matched"`
	Updated       int  `json:"updated"`
	AlreadyMapped int  `json:"already_mapped"`
	Failed        int  `json:"failed"`
}

func (s *Server) resolveBookingPayoutOccupancy(
	ctx context.Context,
	pid int64,
	referenceNumber, checkInDate, checkOutDate, guestName string,
	loc *time.Location,
) (*store.Occupancy, error) {
	return s.Store.FindOrCreateOccupancyForPayoutStayDates(
		ctx,
		pid,
		referenceNumber,
		checkInDate,
		checkOutDate,
		guestName,
		loc,
	)
}

func (s *Server) importFinanceBookingPayouts(w http.ResponseWriter, r *http.Request) {
	actor, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelWrite)
	if !ok {
		return
	}
	prop, err := s.Store.GetProperty(r.Context(), pid)
	if err != nil {
		WriteError(w, http.StatusNotFound, "property not found")
		return
	}
	loc, err := time.LoadLocation(prop.Timezone)
	if err != nil {
		loc = time.UTC
	}
	r.Body = http.MaxBytesReader(w, r.Body, (25<<20)+(1<<20))
	if err := r.ParseMultipartForm(25 << 20); err != nil {
		WriteError(w, http.StatusBadRequest, "invalid multipart form")
		return
	}
	file, _, err := r.FormFile("file")
	if err != nil {
		WriteError(w, http.StatusBadRequest, "missing file")
		return
	}
	defer file.Close()
	rows, warnings, err := parseBookingPayoutCSV(file, loc)
	if err != nil {
		WriteError(w, http.StatusBadRequest, err.Error())
		return
	}
	bookingIncomeCategoryID, err := s.Store.FinanceCategoryIDByCode(r.Context(), pid, "booking_income")
	if err != nil || bookingIncomeCategoryID == 0 {
		WriteError(w, http.StatusBadRequest, "booking_income category missing")
		return
	}
	resp := bookingPayoutImportResponse{OK: true, Warnings: warnings}
	for _, row := range rows {
		existing, err := s.Store.GetBookingPayoutByReference(r.Context(), pid, row.ReferenceNumber)
		if err == nil && existing != nil {
			resp.Duplicates++
			if !existing.OccupancyID.Valid {
				occ, matchErr := s.resolveBookingPayoutOccupancy(
					r.Context(),
					pid,
					row.ReferenceNumber,
					row.CheckInDate,
					row.CheckOutDate,
					row.GuestName,
					loc,
				)
				if matchErr != nil {
					resp.Failed++
					continue
				}
				if occ != nil {
					occID := occ.ID
					_ = s.Store.UpdateBookingPayoutMapping(r.Context(), pid, row.ReferenceNumber, &occID)
					resp.Mapped++
				}
			}
			continue
		}
		if err != nil && err != sql.ErrNoRows {
			resp.Failed++
			continue
		}
		var existingTxID int64
		if tx, err := s.Store.FinanceTransactionBySourceReference(r.Context(), pid, "booking_payout", row.ReferenceNumber); err == nil && tx != nil {
			existingTxID = tx.ID
		}
		var occupancyID sql.NullInt64
		occ, matchErr := s.resolveBookingPayoutOccupancy(
			r.Context(),
			pid,
			row.ReferenceNumber,
			row.CheckInDate,
			row.CheckOutDate,
			row.GuestName,
			loc,
		)
		if matchErr != nil {
			resp.Failed++
			continue
		}
		if occ != nil {
			occupancyID = sql.NullInt64{Int64: occ.ID, Valid: true}
		}
		txInput := &store.FinanceTransaction{
			PropertyID:      pid,
			TransactionDate: row.PayoutDate,
			Direction:       "incoming",
			AmountCents:     row.NetCents,
			CategoryID:      sql.NullInt64{Int64: bookingIncomeCategoryID, Valid: true},
			Note:            sql.NullString{String: "Booking.com payout " + row.ReferenceNumber, Valid: true},
			SourceType:      "booking_payout",
			SourceReference: sql.NullString{String: row.ReferenceNumber, Valid: true},
			IsAutoGenerated: true,
		}
		payout := &store.FinanceBookingPayout{
			PropertyID:             pid,
			ReferenceNumber:        row.ReferenceNumber,
			PayoutID:               sql.NullString{String: row.PayoutID, Valid: row.PayoutID != ""},
			RowType:                sql.NullString{String: row.RowType, Valid: row.RowType != ""},
			CheckInDate:            sql.NullString{String: row.CheckInDate, Valid: row.CheckInDate != ""},
			CheckOutDate:           sql.NullString{String: row.CheckOutDate, Valid: row.CheckOutDate != ""},
			GuestName:              sql.NullString{String: row.GuestName, Valid: row.GuestName != ""},
			ReservationStatus:      sql.NullString{String: row.ReservationStatus, Valid: row.ReservationStatus != ""},
			Currency:               sql.NullString{String: row.Currency, Valid: row.Currency != ""},
			PaymentStatus:          sql.NullString{String: row.PaymentStatus, Valid: row.PaymentStatus != ""},
			AmountCents:            sql.NullInt64{Int64: int64(row.AmountCents), Valid: true},
			CommissionCents:        sql.NullInt64{Int64: int64(row.CommissionCents), Valid: true},
			PaymentServiceFeeCents: sql.NullInt64{Int64: int64(row.PaymentFeeCents), Valid: true},
			NetCents:               row.NetCents,
			PayoutDate:             row.PayoutDate,
			OccupancyID:            occupancyID,
			RawRowJSON:             sql.NullString{String: row.RawJSON, Valid: row.RawJSON != ""},
		}
		if _, err := s.Store.ImportBookingPayoutRow(r.Context(), txInput, payout, existingTxID); err != nil {
			resp.Failed++
			continue
		}
		if occupancyID.Valid {
			resp.Mapped++
		}
		resp.Imported++
	}
	s.audit(r, actor, "finance_booking_payout_import", "property", strconv.FormatInt(pid, 10), "success")
	WriteJSON(w, http.StatusOK, resp)
}

func (s *Server) rematchFinanceBookingPayouts(w http.ResponseWriter, r *http.Request) {
	actor, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelWrite)
	if !ok {
		return
	}
	prop, err := s.Store.GetProperty(r.Context(), pid)
	if err != nil {
		WriteError(w, http.StatusNotFound, "property not found")
		return
	}
	loc, err := time.LoadLocation(prop.Timezone)
	if err != nil {
		loc = time.UTC
	}
	month := strings.TrimSpace(r.URL.Query().Get("month"))
	if month != "" {
		if _, _, err := parseFinanceMonth(month); err != nil {
			WriteError(w, http.StatusBadRequest, "month must be YYYY-MM")
			return
		}
	}
	onlyUnmapped := true
	onlyUnmappedRaw := strings.TrimSpace(strings.ToLower(r.URL.Query().Get("only_unmapped")))
	if onlyUnmappedRaw == "0" || onlyUnmappedRaw == "false" || onlyUnmappedRaw == "no" {
		onlyUnmapped = false
	}
	rows, err := s.Store.ListBookingPayouts(r.Context(), pid, month, nil)
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "database error")
		return
	}
	resp := bookingPayoutRematchResponse{OK: true}
	for _, row := range rows {
		resp.Scanned++
		if onlyUnmapped && row.OccupancyID.Valid {
			resp.AlreadyMapped++
			continue
		}
		occ, err := s.resolveBookingPayoutOccupancy(
			r.Context(),
			pid,
			row.ReferenceNumber,
			strings.TrimSpace(row.CheckInDate.String),
			strings.TrimSpace(row.CheckOutDate.String),
			fixCSVMojibake(strings.TrimSpace(row.GuestName.String)),
			loc,
		)
		if err != nil {
			resp.Failed++
			continue
		}
		if occ == nil {
			continue
		}
		resp.Matched++
		occID := occ.ID
		if err := s.Store.UpdateBookingPayoutMapping(r.Context(), pid, row.ReferenceNumber, &occID); err != nil {
			resp.Failed++
			continue
		}
		resp.Updated++
	}
	s.audit(r, actor, "finance_booking_payout_rematch", "property", strconv.FormatInt(pid, 10), "success")
	WriteJSON(w, http.StatusOK, resp)
}

func (s *Server) mapFinanceBookingPayout(w http.ResponseWriter, r *http.Request) {
	actor, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelWrite)
	if !ok {
		return
	}
	referenceNumber := strings.TrimSpace(chi.URLParam(r, "referenceNumber"))
	if referenceNumber == "" {
		WriteError(w, http.StatusBadRequest, "referenceNumber required")
		return
	}
	var body struct {
		OccupancyID *int64 `json:"occupancy_id"`
	}
	if err := ReadJSON(r, &body); err != nil {
		WriteError(w, http.StatusBadRequest, "invalid json")
		return
	}
	if _, err := s.Store.GetBookingPayoutByReference(r.Context(), pid, referenceNumber); err != nil {
		WriteError(w, http.StatusNotFound, "booking payout not found")
		return
	}
	var targetID *int64
	if body.OccupancyID != nil && *body.OccupancyID > 0 {
		if _, err := s.Store.GetOccupancyByID(r.Context(), pid, *body.OccupancyID); err != nil {
			WriteError(w, http.StatusBadRequest, "invalid occupancy_id")
			return
		}
		targetID = body.OccupancyID
	}
	if err := s.Store.UpdateBookingPayoutMapping(r.Context(), pid, referenceNumber, targetID); err != nil {
		WriteError(w, http.StatusInternalServerError, "mapping update failed")
		return
	}
	s.audit(r, actor, "finance_booking_payout_map", "finance_booking_payout", referenceNumber, "success")
	WriteJSON(w, http.StatusOK, map[string]interface{}{
		"ok":               true,
		"reference_number": referenceNumber,
		"occupancy_id":     targetID,
	})
}

func (s *Server) createFinanceBookingPayoutStay(w http.ResponseWriter, r *http.Request) {
	actor, pid, ok := s.requirePropertyModuleAccess(w, r, permissions.Finance, permissions.LevelWrite)
	if !ok {
		return
	}
	referenceNumber := strings.TrimSpace(chi.URLParam(r, "referenceNumber"))
	if referenceNumber == "" {
		WriteError(w, http.StatusBadRequest, "referenceNumber required")
		return
	}
	payout, err := s.Store.GetBookingPayoutByReference(r.Context(), pid, referenceNumber)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			WriteError(w, http.StatusNotFound, "booking payout not found")
			return
		}
		WriteError(w, http.StatusInternalServerError, "database error")
		return
	}
	prop, err := s.Store.GetProperty(r.Context(), pid)
	if err != nil {
		WriteError(w, http.StatusNotFound, "property not found")
		return
	}
	loc, err := time.LoadLocation(prop.Timezone)
	if err != nil {
		loc = time.UTC
	}
	syntheticUID := "booking_payout:" + referenceNumber
	preExistingSynthetic, err := s.Store.GetOccupancyBySourceEventUID(r.Context(), pid, syntheticUID)
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "database error")
		return
	}
	occ, err := s.resolveBookingPayoutOccupancy(
		r.Context(),
		pid,
		referenceNumber,
		strings.TrimSpace(payout.CheckInDate.String),
		strings.TrimSpace(payout.CheckOutDate.String),
		fixCSVMojibake(strings.TrimSpace(payout.GuestName.String)),
		loc,
	)
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "failed to create stay")
		return
	}
	if occ == nil {
		WriteError(w, http.StatusBadRequest, "cannot create stay: missing or invalid check-in/check-out dates")
		return
	}
	occID := occ.ID
	if err := s.Store.UpdateBookingPayoutMapping(r.Context(), pid, referenceNumber, &occID); err != nil {
		WriteError(w, http.StatusInternalServerError, "mapping update failed")
		return
	}
	created := preExistingSynthetic == nil && (occ.SourceType == "booking_payout" || strings.HasPrefix(occ.SourceEventUID, "booking_payout:"))
	s.audit(r, actor, "finance_booking_payout_create_stay", "finance_booking_payout", referenceNumber, "success")
	WriteJSON(w, http.StatusOK, map[string]interface{}{
		"ok":               true,
		"reference_number": referenceNumber,
		"occupancy_id":     occID,
		"created":          created,
	})
}

func parseBookingPayoutCSV(in io.Reader, loc *time.Location) ([]bookingPayoutCSVRow, []string, error) {
	r := csv.NewReader(in)
	r.FieldsPerRecord = -1
	r.TrimLeadingSpace = true
	header, err := r.Read()
	if err != nil {
		return nil, nil, fmt.Errorf("invalid csv header")
	}
	idx := map[string]int{}
	for i, h := range header {
		key := strings.ToLower(strings.TrimSpace(strings.TrimPrefix(h, "\ufeff")))
		idx[key] = i
	}
	if _, ok := idx["reference number"]; !ok {
		if i, aliasOK := idx["refference number"]; aliasOK {
			idx["reference number"] = i
		}
	}
	required := []string{"reference number", "net", "payout date"}
	for _, k := range required {
		if _, ok := idx[k]; !ok {
			return nil, nil, fmt.Errorf("csv missing required column: %s", k)
		}
	}
	warnings := []string{}
	out := make([]bookingPayoutCSVRow, 0)
	line := 1
	for {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		line++
		if err != nil {
			warnings = append(warnings, fmt.Sprintf("line %d skipped: %v", line, err))
			continue
		}
		ref := csvVal(rec, idx, "reference number")
		if ref == "" {
			warnings = append(warnings, fmt.Sprintf("line %d skipped: missing reference number", line))
			continue
		}
		net, err := parseMoneyToCents(csvVal(rec, idx, "net"))
		if err != nil {
			warnings = append(warnings, fmt.Sprintf("line %d skipped: invalid net", line))
			continue
		}
		payoutDate, err := parseBookingDate(csvVal(rec, idx, "payout date"), loc)
		if err != nil {
			warnings = append(warnings, fmt.Sprintf("line %d skipped: invalid payout date", line))
			continue
		}
		amount, _ := parseMoneyToCents(csvVal(rec, idx, "amount"))
		commission, _ := parseMoneyToCents(csvVal(rec, idx, "commission"))
		payFee, _ := parseMoneyToCents(csvVal(rec, idx, "payments service fee"))
		checkIn, _ := parseBookingDateOnly(csvVal(rec, idx, "check-in"), loc)
		checkOut, _ := parseBookingDateOnly(csvVal(rec, idx, "checkout"), loc)
		rawMap := map[string]string{}
		for k, i := range idx {
			if i >= 0 && i < len(rec) {
				rawMap[k] = fixCSVMojibake(rec[i])
			}
		}
		rawJSON, _ := json.Marshal(rawMap)
		out = append(out, bookingPayoutCSVRow{
			ReferenceNumber:   ref,
			RowType:           csvVal(rec, idx, "type"),
			CheckInDate:       checkIn,
			CheckOutDate:      checkOut,
			GuestName:         fixCSVMojibake(csvVal(rec, idx, "guest name")),
			ReservationStatus: csvVal(rec, idx, "reservation status"),
			Currency:          csvVal(rec, idx, "currency"),
			PaymentStatus:     csvVal(rec, idx, "payment status"),
			AmountCents:       amount,
			CommissionCents:   commission,
			PaymentFeeCents:   payFee,
			NetCents:          net,
			PayoutDate:        payoutDate,
			PayoutID:          csvVal(rec, idx, "payout id"),
			RawJSON:           string(rawJSON),
		})
	}
	return out, warnings, nil
}

func csvVal(rec []string, idx map[string]int, key string) string {
	i, ok := idx[key]
	if !ok || i < 0 || i >= len(rec) {
		return ""
	}
	return strings.TrimSpace(rec[i])
}

func parseMoneyToCents(v string) (int, error) {
	s := strings.TrimSpace(v)
	if s == "" {
		return 0, nil
	}
	s = strings.ReplaceAll(s, " ", "")
	s = strings.ReplaceAll(s, ",", ".")
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 0, err
	}
	return int(math.Round(f * 100)), nil
}

func parseBookingDate(v string, loc *time.Location) (time.Time, error) {
	t, err := time.ParseInLocation("2 Jan 2006", strings.TrimSpace(v), loc)
	if err != nil {
		return time.Time{}, err
	}
	return time.Date(t.Year(), t.Month(), t.Day(), 12, 0, 0, 0, loc).UTC(), nil
}

func parseBookingDateOnly(v string, loc *time.Location) (string, error) {
	t, err := time.ParseInLocation("2 Jan 2006", strings.TrimSpace(v), loc)
	if err != nil {
		return "", err
	}
	return t.Format("2006-01-02"), nil
}

func (s *Server) parseTransactionCreateRequest(r *http.Request, propertyID int64, loc *time.Location) (*store.FinanceTransaction, *pendingAttachment, error) {
	ct := strings.ToLower(strings.TrimSpace(r.Header.Get("Content-Type")))
	var dateRaw, direction string
	var amountCents int
	var categoryID int64
	var note string
	var pending *pendingAttachment

	if strings.HasPrefix(ct, "multipart/form-data") {
		r.Body = http.MaxBytesReader(nil, r.Body, (20<<20)+(1<<20))
		if err := r.ParseMultipartForm(20 << 20); err != nil {
			return nil, nil, fmt.Errorf("invalid multipart body")
		}
		dateRaw = strings.TrimSpace(r.FormValue("transaction_date"))
		direction = strings.TrimSpace(r.FormValue("direction"))
		note = strings.TrimSpace(r.FormValue("note"))
		amountRaw := strings.TrimSpace(r.FormValue("amount_cents"))
		if amountRaw == "" {
			amountRaw = strings.TrimSpace(r.FormValue("amount"))
		}
		if amountRaw == "" {
			return nil, nil, fmt.Errorf("amount_cents is required")
		}
		v, err := strconv.Atoi(amountRaw)
		if err != nil {
			return nil, nil, fmt.Errorf("amount_cents must be a number")
		}
		amountCents = v
		if catRaw := strings.TrimSpace(r.FormValue("category_id")); catRaw != "" {
			cid, err := strconv.ParseInt(catRaw, 10, 64)
			if err != nil {
				return nil, nil, fmt.Errorf("category_id must be a number")
			}
			categoryID = cid
		}
		file, header, err := r.FormFile("attachment")
		if err == nil {
			pending = &pendingAttachment{file: file, header: header}
		}
	} else {
		var body struct {
			TransactionDate string `json:"transaction_date"`
			Direction       string `json:"direction"`
			AmountCents     int    `json:"amount_cents"`
			CategoryID      *int64 `json:"category_id"`
			Note            string `json:"note"`
			// attachment_path is intentionally ignored: attachments must be
			// uploaded via multipart so the server controls their storage path.
		}
		if err := ReadJSON(r, &body); err != nil {
			return nil, nil, fmt.Errorf("invalid json")
		}
		dateRaw = strings.TrimSpace(body.TransactionDate)
		direction = strings.TrimSpace(body.Direction)
		amountCents = body.AmountCents
		note = strings.TrimSpace(body.Note)
		if body.CategoryID != nil {
			categoryID = *body.CategoryID
		}
	}
	if dateRaw == "" {
		return nil, nil, fmt.Errorf("transaction_date is required")
	}
	txDate, err := parseFinanceDate(dateRaw, loc)
	if err != nil {
		return nil, nil, fmt.Errorf("transaction_date must be RFC3339 or YYYY-MM-DD")
	}
	if direction != "incoming" && direction != "outgoing" {
		return nil, nil, fmt.Errorf("direction must be incoming or outgoing")
	}
	if amountCents < 0 {
		return nil, nil, fmt.Errorf("amount_cents must be >= 0")
	}
	if categoryID > 0 {
		if _, err := s.Store.GetFinanceCategoryByID(r.Context(), propertyID, categoryID); err != nil {
			return nil, nil, fmt.Errorf("invalid category_id")
		}
	}
	return &store.FinanceTransaction{
		PropertyID:      propertyID,
		TransactionDate: txDate,
		Direction:       direction,
		AmountCents:     amountCents,
		CategoryID:      sql.NullInt64{Int64: categoryID, Valid: categoryID > 0},
		Note:            sql.NullString{String: note, Valid: note != ""},
		SourceType:      "manual",
		IsAutoGenerated: false,
	}, pending, nil
}

type pendingAttachment struct {
	file   multipart.File
	header *multipart.FileHeader
}

func (p *pendingAttachment) Close() {
	if p != nil && p.file != nil {
		_ = p.file.Close()
	}
}

func parseFinanceDate(raw string, loc *time.Location) (time.Time, error) {
	raw = strings.TrimSpace(raw)
	if t, err := time.Parse(time.RFC3339, raw); err == nil {
		return t.UTC(), nil
	}
	if t, err := time.ParseInLocation("2006-01-02", raw, loc); err == nil {
		// Use local noon to avoid month drift in positive-offset timezones.
		return time.Date(t.Year(), t.Month(), t.Day(), 12, 0, 0, 0, loc).UTC(), nil
	}
	return time.Time{}, fmt.Errorf("invalid date")
}

func (s *Server) saveFinanceAttachment(propertyID, transactionID int64, header *multipart.FileHeader, file multipart.File) (string, error) {
	if header == nil || file == nil {
		return "", nil
	}
	if transactionID <= 0 {
		return "", fmt.Errorf("invalid transaction id")
	}
	base := filepath.Base(header.Filename)
	base = strings.ReplaceAll(base, " ", "_")
	if base == "." || base == "" || base == "/" || strings.Contains(base, "..") {
		return "", fmt.Errorf("invalid attachment filename")
	}
	baseDir := strings.TrimSpace(s.DataDir)
	if baseDir == "" {
		baseDir = "./data"
	}
	dir := filepath.Join(baseDir, "attachments", fmt.Sprintf("%d", propertyID), fmt.Sprintf("%d", transactionID))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("unable to create attachment directory")
	}
	fullPath := filepath.Join(dir, base)
	dst, err := os.Create(fullPath)
	if err != nil {
		return "", fmt.Errorf("unable to create attachment file")
	}
	defer dst.Close()
	if _, err := io.Copy(dst, file); err != nil {
		return "", fmt.Errorf("unable to save attachment")
	}
	return filepath.ToSlash(filepath.Join("attachments", fmt.Sprintf("%d", propertyID), fmt.Sprintf("%d", transactionID), base)), nil
}

func ptrString(v *string) string {
	if v == nil {
		return ""
	}
	return *v
}

func parseFinanceMonth(month string) (int, int, error) {
	var y, m int
	if _, err := fmt.Sscanf(month, "%d-%d", &y, &m); err != nil {
		return 0, 0, fmt.Errorf("month must be YYYY-MM")
	}
	if y < 2000 || y > 3000 || m < 1 || m > 12 {
		return 0, 0, fmt.Errorf("month must be YYYY-MM")
	}
	return y, m, nil
}
