package store

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"pms/backend/internal/auth"
	"pms/backend/internal/testutil"
)

func setupFinanceProperty(t *testing.T, st *Store) int64 {
	t.Helper()
	ctx := context.Background()
	hash, _ := auth.HashPassword("secret123")
	u, err := st.CreateUser(ctx, "owner@finance.test", hash, "owner")
	if err != nil {
		t.Fatal(err)
	}
	p, err := st.CreateProperty(ctx, u.ID, "FinanceTest", "UTC", "en")
	if err != nil {
		t.Fatal(err)
	}
	return p.ID
}

func categoryIDByCode(t *testing.T, st *Store, pid int64, code string) int64 {
	t.Helper()
	rows, err := st.ListFinanceCategories(context.Background(), pid)
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range rows {
		if c.Code == code {
			return c.ID
		}
	}
	t.Fatalf("category %q not found", code)
	return 0
}

func TestOpenFinanceMonth_IsIdempotentForRecurringRules(t *testing.T) {
	st := &Store{DB: testutil.OpenTestDB(t)}
	pid := setupFinanceProperty(t, st)
	loc := time.UTC
	month := time.Now().UTC().Format("2006-01")

	rule, err := st.CreateFinanceRecurringRule(context.Background(), &FinanceRecurringRule{
		PropertyID:    pid,
		Title:         "Internet monthly",
		CategoryID:    sql.NullInt64{},
		AmountCents:   2500,
		Direction:     "outgoing",
		Frequency:     "monthly",
		StartMonth:    month,
		EffectiveFrom: time.Now().UTC().Add(-24 * time.Hour),
		Active:        true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if rule.ID == 0 {
		t.Fatalf("rule id missing")
	}

	if _, err := st.OpenFinanceMonth(context.Background(), pid, month, nil, loc); err != nil {
		t.Fatal(err)
	}
	if _, err := st.OpenFinanceMonth(context.Background(), pid, month, nil, loc); err != nil {
		t.Fatal(err)
	}

	txs, err := st.ListFinanceTransactions(context.Background(), pid, month, 0, 0)
	if err != nil {
		t.Fatal(err)
	}
	count := 0
	for _, tx := range txs {
		if tx.SourceType == "recurring_rule" {
			count++
		}
	}
	if count != 1 {
		t.Fatalf("recurring transactions = %d, want 1", count)
	}
}

func TestComputeFinanceSummary_CalculatesCleanerMargin(t *testing.T) {
	st := &Store{DB: testutil.OpenTestDB(t)}
	pid := setupFinanceProperty(t, st)
	month := "2026-04"
	tDate := time.Date(2026, 4, 5, 9, 0, 0, 0, time.UTC)

	bookingCat := categoryIDByCode(t, st, pid, "booking_income")
	cleaningCat := categoryIDByCode(t, st, pid, "cleaning_salary")

	_, err := st.CreateFinanceTransaction(context.Background(), &FinanceTransaction{
		PropertyID:      pid,
		TransactionDate: tDate,
		Direction:       "incoming",
		AmountCents:     100000,
		CategoryID:      sql.NullInt64{Int64: bookingCat, Valid: true},
		SourceType:      "manual",
	})
	if err != nil {
		t.Fatal(err)
	}
	_, err = st.CreateFinanceTransaction(context.Background(), &FinanceTransaction{
		PropertyID:      pid,
		TransactionDate: tDate,
		Direction:       "outgoing",
		AmountCents:     40000,
		CategoryID:      sql.NullInt64{Int64: cleaningCat, Valid: true},
		SourceType:      "cleaning_salary",
		SourceReference: sql.NullString{String: month, Valid: true},
		IsAutoGenerated: true,
	})
	if err != nil {
		t.Fatal(err)
	}

	sum, err := st.ComputeFinanceSummary(context.Background(), pid, month)
	if err != nil {
		t.Fatal(err)
	}
	if sum.MonthlyPropertyIncomeCents != 100000 {
		t.Fatalf("monthly property income = %d, want 100000", sum.MonthlyPropertyIncomeCents)
	}
	if sum.CleanerExpenseCents != 40000 {
		t.Fatalf("cleaner expense = %d, want 40000", sum.CleanerExpenseCents)
	}
	if sum.CleanerMargin < 0.399 || sum.CleanerMargin > 0.401 {
		t.Fatalf("cleaner margin = %f, want ~0.4", sum.CleanerMargin)
	}
}

func TestOpenFinanceMonth_PositiveTimezoneKeepsTargetMonth(t *testing.T) {
	st := &Store{DB: testutil.OpenTestDB(t)}
	pid := setupFinanceProperty(t, st)
	loc := time.FixedZone("UTC+2", 2*60*60)
	month := "2026-04"

	rule, err := st.CreateFinanceRecurringRule(context.Background(), &FinanceRecurringRule{
		PropertyID:    pid,
		Title:         "TZ recurring",
		CategoryID:    sql.NullInt64{},
		AmountCents:   1234,
		Direction:     "outgoing",
		Frequency:     "monthly",
		StartMonth:    month,
		EffectiveFrom: time.Now().UTC().Add(-24 * time.Hour),
		Active:        true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if rule.ID == 0 {
		t.Fatalf("rule id missing")
	}

	if _, err := st.OpenFinanceMonth(context.Background(), pid, month, nil, loc); err != nil {
		t.Fatal(err)
	}
	rows, err := st.ListFinanceTransactions(context.Background(), pid, month, 0, 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(rows) == 0 {
		t.Fatalf("expected recurring row in month %s", month)
	}
}

func TestFindOrCreateOccupancyForPayoutStayDates_CreatesHistoricalStay(t *testing.T) {
	st := &Store{DB: testutil.OpenTestDB(t)}
	pid := setupFinanceProperty(t, st)
	loc := time.FixedZone("UTC+2", 2*60*60)

	occ, err := st.FindOrCreateOccupancyForPayoutStayDates(
		context.Background(),
		pid,
		"BP-1001",
		"2025-01-10",
		"2025-01-12",
		"Jane Guest",
		loc,
	)
	if err != nil {
		t.Fatal(err)
	}
	if occ == nil {
		t.Fatalf("expected occupancy to be created")
	}
	if occ.SourceType != "booking_payout" {
		t.Fatalf("source_type=%q want booking_payout", occ.SourceType)
	}
	if occ.SourceEventUID != "booking_payout:BP-1001" {
		t.Fatalf("source_event_uid=%q want booking_payout:BP-1001", occ.SourceEventUID)
	}
	if got := occ.StartAt.In(loc).Format("2006-01-02"); got != "2025-01-10" {
		t.Fatalf("start date=%s want 2025-01-10", got)
	}
	if got := occ.EndAt.In(loc).Format("2006-01-02"); got != "2025-01-12" {
		t.Fatalf("end date=%s want 2025-01-12", got)
	}
	if !occ.GuestDisplayName.Valid || occ.GuestDisplayName.String != "Jane Guest" {
		t.Fatalf("guest_display_name=%v want Jane Guest", occ.GuestDisplayName)
	}
}

func TestFindOrCreateOccupancyForPayoutStayDates_ReusesExistingStay(t *testing.T) {
	st := &Store{DB: testutil.OpenTestDB(t)}
	pid := setupFinanceProperty(t, st)
	loc := time.UTC
	ctx := context.Background()

	runID, err := st.StartOccupancySyncRun(ctx, pid, "test")
	if err != nil {
		t.Fatal(err)
	}
	existing := &Occupancy{
		PropertyID:     pid,
		SourceType:     "booking_ics",
		SourceEventUID: "ics-uid-1",
		StartAt:        time.Date(2025, 2, 3, 0, 0, 0, 0, loc),
		EndAt:          time.Date(2025, 2, 6, 0, 0, 0, 0, loc),
		Status:         "active",
		RawSummary:     sql.NullString{String: "ICS guest", Valid: true},
		ContentHash:    "ics-hash-1",
	}
	if err := st.UpsertOccupancy(ctx, existing, runID); err != nil {
		t.Fatal(err)
	}
	existingSaved, err := st.GetOccupancyBySourceEventUID(ctx, pid, "ics-uid-1")
	if err != nil || existingSaved == nil {
		t.Fatalf("expected existing occupancy err=%v", err)
	}

	occ, err := st.FindOrCreateOccupancyForPayoutStayDates(
		ctx,
		pid,
		"BP-2002",
		"2025-02-03",
		"2025-02-06",
		"Guest Changed Name",
		loc,
	)
	if err != nil {
		t.Fatal(err)
	}
	if occ == nil {
		t.Fatalf("expected existing occupancy")
	}
	if occ.ID != existingSaved.ID {
		t.Fatalf("occupancy id=%d want existing id=%d", occ.ID, existingSaved.ID)
	}
	payoutSynthetic, err := st.GetOccupancyBySourceEventUID(ctx, pid, "booking_payout:BP-2002")
	if err != nil {
		t.Fatal(err)
	}
	if payoutSynthetic != nil {
		t.Fatalf("did not expect synthetic payout occupancy when matching occupancy exists")
	}
}
