package store

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

type FinanceCategory struct {
	ID                         int64
	PropertyID                 sql.NullInt64
	Code                       string
	Title                      string
	Direction                  string
	CountsTowardPropertyIncome bool
	Active                     bool
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

type FinanceTransaction struct {
	ID                 int64
	PropertyID         int64
	TransactionDate    time.Time
	Direction          string
	AmountCents        int
	CategoryID         sql.NullInt64
	Note               sql.NullString
	SourceType         string
	SourceReference    sql.NullString
	IsAutoGenerated    bool
	AttachmentPath     sql.NullString
	CreatedAt          time.Time
	UpdatedAt          time.Time
	CategoryCode       sql.NullString
	CategoryTitle      sql.NullString
	CountsTowardIncome bool
	MappedToStay       bool
}

type FinanceRecurringRule struct {
	ID            int64
	PropertyID    int64
	Title         string
	CategoryID    sql.NullInt64
	AmountCents   int
	Direction     string
	Frequency     string
	StartMonth    string
	EndMonth      sql.NullString
	EffectiveFrom time.Time
	EffectiveTo   sql.NullTime
	Active        bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type FinanceSummary struct {
	Month                      string
	TotalIncomingCents         int
	TotalOutgoingCents         int
	MonthlyIncomingCents       int
	MonthlyOutgoingCents       int
	MonthlyNetCents            int
	PropertyIncomeCents        int
	MonthlyPropertyIncomeCents int
	CleanerExpenseCents        int
	CleanerMargin              float64
	Breakdown                  []FinanceCategoryBreakdown
}

type FinanceCategoryBreakdown struct {
	CategoryID    sql.NullInt64
	CategoryCode  sql.NullString
	CategoryTitle sql.NullString
	IncomingCents int
	OutgoingCents int
}

func (s *Store) ListFinanceCategories(ctx context.Context, propertyID int64) ([]FinanceCategory, error) {
	rows, err := s.DB.QueryContext(ctx, `
		SELECT id, property_id, code, title, direction, counts_toward_property_income, active, created_at, updated_at
		FROM finance_categories
		WHERE active = 1 AND (property_id IS NULL OR property_id = ?)
		ORDER BY CASE WHEN property_id IS NULL THEN 1 ELSE 0 END, title ASC`, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := make([]FinanceCategory, 0)
	for rows.Next() {
		var c FinanceCategory
		var income, active int
		var created, updated string
		if err := rows.Scan(&c.ID, &c.PropertyID, &c.Code, &c.Title, &c.Direction, &income, &active, &created, &updated); err != nil {
			return nil, err
		}
		c.CountsTowardPropertyIncome = income == 1
		c.Active = active == 1
		c.CreatedAt, _ = time.Parse(time.RFC3339, created)
		c.UpdatedAt, _ = time.Parse(time.RFC3339, updated)
		out = append(out, c)
	}
	return out, rows.Err()
}

func (s *Store) CreateFinanceCategory(ctx context.Context, propertyID int64, code, title, direction string, countsTowardIncome bool) (*FinanceCategory, error) {
	now := time.Now().UTC().Format(time.RFC3339)
	income := 0
	if countsTowardIncome {
		income = 1
	}
	res, err := s.DB.ExecContext(ctx, `
		INSERT INTO finance_categories (property_id, code, title, direction, counts_toward_property_income, active, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, 1, ?, ?)`, propertyID, code, title, direction, income, now, now)
	if err != nil {
		return nil, err
	}
	id, _ := res.LastInsertId()
	return s.GetFinanceCategoryByID(ctx, propertyID, id)
}

func (s *Store) GetFinanceCategoryByID(ctx context.Context, propertyID, categoryID int64) (*FinanceCategory, error) {
	var c FinanceCategory
	var income, active int
	var created, updated string
	err := s.DB.QueryRowContext(ctx, `
		SELECT id, property_id, code, title, direction, counts_toward_property_income, active, created_at, updated_at
		FROM finance_categories
		WHERE id = ? AND active = 1 AND (property_id IS NULL OR property_id = ?)`, categoryID, propertyID).
		Scan(&c.ID, &c.PropertyID, &c.Code, &c.Title, &c.Direction, &income, &active, &created, &updated)
	if err != nil {
		return nil, err
	}
	c.CountsTowardPropertyIncome = income == 1
	c.Active = active == 1
	c.CreatedAt, _ = time.Parse(time.RFC3339, created)
	c.UpdatedAt, _ = time.Parse(time.RFC3339, updated)
	return &c, nil
}

func (s *Store) ListFinanceTransactions(ctx context.Context, propertyID int64, month string, limit, offset int) ([]FinanceTransaction, error) {
	query := `
		SELECT ft.id, ft.property_id, ft.transaction_date, ft.direction, ft.amount_cents, ft.category_id,
			ft.note, ft.source_type, ft.source_reference_id, ft.is_auto_generated, ft.attachment_path, ft.created_at, ft.updated_at,
			fc.code, fc.title, COALESCE(fc.counts_toward_property_income, 0),
			COALESCE(CASE WHEN fbp.occupancy_id IS NOT NULL THEN 1 ELSE 0 END, 0)
		FROM finance_transactions ft
		LEFT JOIN finance_categories fc ON fc.id = ft.category_id
		LEFT JOIN finance_booking_payouts fbp
		  ON fbp.property_id = ft.property_id
		 AND fbp.reference_number = ft.source_reference_id
		WHERE ft.property_id = ?`
	args := []interface{}{propertyID}
	if month != "" {
		query += ` AND substr(ft.transaction_date, 1, 7) = ?`
		args = append(args, month)
	}
	query += ` ORDER BY ft.transaction_date DESC, ft.id DESC`
	if limit > 0 {
		query += ` LIMIT ? OFFSET ?`
		args = append(args, limit, offset)
	}
	rows, err := s.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanFinanceTransactionsRows(rows)
}

func (s *Store) CreateFinanceTransaction(ctx context.Context, row *FinanceTransaction) (*FinanceTransaction, error) {
	now := time.Now().UTC().Format(time.RFC3339)
	auto := 0
	if row.IsAutoGenerated {
		auto = 1
	}
	res, err := s.DB.ExecContext(ctx, `
		INSERT INTO finance_transactions (
			property_id, transaction_date, direction, amount_cents, category_id, note,
			source_type, source_reference_id, is_auto_generated, attachment_path, created_at, updated_at
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		row.PropertyID, row.TransactionDate.UTC().Format(time.RFC3339), row.Direction, row.AmountCents, nullInt64Value(row.CategoryID),
		nullStringValue(row.Note), row.SourceType, nullStringValue(row.SourceReference), auto, nullStringValue(row.AttachmentPath), now, now)
	if err != nil {
		return nil, err
	}
	id, _ := res.LastInsertId()
	return s.GetFinanceTransactionByID(ctx, row.PropertyID, id)
}

func (s *Store) GetFinanceTransactionByID(ctx context.Context, propertyID, id int64) (*FinanceTransaction, error) {
	rows, err := s.DB.QueryContext(ctx, `
		SELECT ft.id, ft.property_id, ft.transaction_date, ft.direction, ft.amount_cents, ft.category_id,
			ft.note, ft.source_type, ft.source_reference_id, ft.is_auto_generated, ft.attachment_path, ft.created_at, ft.updated_at,
			fc.code, fc.title, COALESCE(fc.counts_toward_property_income, 0),
			COALESCE(CASE WHEN fbp.occupancy_id IS NOT NULL THEN 1 ELSE 0 END, 0)
		FROM finance_transactions ft
		LEFT JOIN finance_categories fc ON fc.id = ft.category_id
		LEFT JOIN finance_booking_payouts fbp
		  ON fbp.property_id = ft.property_id
		 AND fbp.reference_number = ft.source_reference_id
		WHERE ft.property_id = ? AND ft.id = ?
		LIMIT 1`, propertyID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	list, err := scanFinanceTransactionsRows(rows)
	if err != nil {
		return nil, err
	}
	if len(list) == 0 {
		return nil, sql.ErrNoRows
	}
	return &list[0], nil
}

func (s *Store) UpdateFinanceTransaction(ctx context.Context, propertyID, id int64, txDate *time.Time, direction *string, amountCents *int, categoryID *int64, note *string, attachmentPath *string) (*FinanceTransaction, error) {
	row, err := s.GetFinanceTransactionByID(ctx, propertyID, id)
	if err != nil {
		return nil, err
	}
	if row.IsAutoGenerated {
		return nil, fmt.Errorf("auto_generated_transactions_are_read_only")
	}
	if txDate != nil {
		row.TransactionDate = txDate.UTC()
	}
	if direction != nil {
		row.Direction = *direction
	}
	if amountCents != nil {
		row.AmountCents = *amountCents
	}
	if categoryID != nil {
		row.CategoryID = sql.NullInt64{Int64: *categoryID, Valid: *categoryID > 0}
	}
	if note != nil {
		row.Note = sql.NullString{String: *note, Valid: *note != ""}
	}
	if attachmentPath != nil {
		row.AttachmentPath = sql.NullString{String: *attachmentPath, Valid: *attachmentPath != ""}
	}
	now := time.Now().UTC().Format(time.RFC3339)
	_, err = s.DB.ExecContext(ctx, `
		UPDATE finance_transactions
		SET transaction_date = ?, direction = ?, amount_cents = ?, category_id = ?, note = ?, attachment_path = ?, updated_at = ?
		WHERE id = ? AND property_id = ?`,
		row.TransactionDate.UTC().Format(time.RFC3339), row.Direction, row.AmountCents, nullInt64Value(row.CategoryID),
		nullStringValue(row.Note), nullStringValue(row.AttachmentPath), now, id, propertyID)
	if err != nil {
		return nil, err
	}
	return s.GetFinanceTransactionByID(ctx, propertyID, id)
}

func (s *Store) DeleteFinanceTransaction(ctx context.Context, propertyID, id int64) error {
	res, err := s.DB.ExecContext(ctx, `DELETE FROM finance_transactions WHERE id = ? AND property_id = ? AND is_auto_generated = 0`, id, propertyID)
	if err != nil {
		return err
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return sql.ErrNoRows
	}
	return nil
}

func (s *Store) ListFinanceRecurringRules(ctx context.Context, propertyID int64) ([]FinanceRecurringRule, error) {
	rows, err := s.DB.QueryContext(ctx, `
		SELECT id, property_id, title, category_id, amount_cents, direction, frequency, start_month, end_month,
			effective_from, effective_to, active, created_at, updated_at
		FROM finance_recurring_rules
		WHERE property_id = ?
		ORDER BY active DESC, start_month DESC, id DESC`, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := make([]FinanceRecurringRule, 0)
	for rows.Next() {
		var r FinanceRecurringRule
		var effFrom, created, updated string
		var effTo sql.NullString
		var active int
		if err := rows.Scan(&r.ID, &r.PropertyID, &r.Title, &r.CategoryID, &r.AmountCents, &r.Direction, &r.Frequency, &r.StartMonth, &r.EndMonth,
			&effFrom, &effTo, &active, &created, &updated); err != nil {
			return nil, err
		}
		r.EffectiveFrom, _ = time.Parse(time.RFC3339, effFrom)
		if effTo.Valid && effTo.String != "" {
			t, _ := time.Parse(time.RFC3339, effTo.String)
			r.EffectiveTo = sql.NullTime{Time: t, Valid: true}
		}
		r.CreatedAt, _ = time.Parse(time.RFC3339, created)
		r.UpdatedAt, _ = time.Parse(time.RFC3339, updated)
		r.Active = active == 1
		out = append(out, r)
	}
	return out, rows.Err()
}

func (s *Store) CreateFinanceRecurringRule(ctx context.Context, row *FinanceRecurringRule) (*FinanceRecurringRule, error) {
	now := time.Now().UTC().Format(time.RFC3339)
	active := 0
	if row.Active {
		active = 1
	}
	var effTo interface{}
	if row.EffectiveTo.Valid {
		effTo = row.EffectiveTo.Time.UTC().Format(time.RFC3339)
	}
	res, err := s.DB.ExecContext(ctx, `
		INSERT INTO finance_recurring_rules (
			property_id, title, category_id, amount_cents, direction, frequency, start_month, end_month,
			effective_from, effective_to, active, created_at, updated_at
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		row.PropertyID, row.Title, nullInt64Value(row.CategoryID), row.AmountCents, row.Direction, "monthly", row.StartMonth, nullStringValue(row.EndMonth),
		row.EffectiveFrom.UTC().Format(time.RFC3339), effTo, active, now, now)
	if err != nil {
		return nil, err
	}
	id, _ := res.LastInsertId()
	return s.GetFinanceRecurringRuleByID(ctx, row.PropertyID, id)
}

func (s *Store) GetFinanceRecurringRuleByID(ctx context.Context, propertyID, id int64) (*FinanceRecurringRule, error) {
	var r FinanceRecurringRule
	var effFrom, created, updated string
	var effTo sql.NullString
	var active int
	err := s.DB.QueryRowContext(ctx, `
		SELECT id, property_id, title, category_id, amount_cents, direction, frequency, start_month, end_month,
			effective_from, effective_to, active, created_at, updated_at
		FROM finance_recurring_rules
		WHERE property_id = ? AND id = ?`, propertyID, id).
		Scan(&r.ID, &r.PropertyID, &r.Title, &r.CategoryID, &r.AmountCents, &r.Direction, &r.Frequency, &r.StartMonth, &r.EndMonth,
			&effFrom, &effTo, &active, &created, &updated)
	if err != nil {
		return nil, err
	}
	r.EffectiveFrom, _ = time.Parse(time.RFC3339, effFrom)
	if effTo.Valid && effTo.String != "" {
		t, _ := time.Parse(time.RFC3339, effTo.String)
		r.EffectiveTo = sql.NullTime{Time: t, Valid: true}
	}
	r.CreatedAt, _ = time.Parse(time.RFC3339, created)
	r.UpdatedAt, _ = time.Parse(time.RFC3339, updated)
	r.Active = active == 1
	return &r, nil
}

func (s *Store) UpdateFinanceRecurringRule(ctx context.Context, propertyID, id int64, title *string, categoryID *int64, amountCents *int, direction *string, startMonth *string, endMonth *string, effectiveFrom *time.Time, effectiveTo *time.Time, active *bool) (*FinanceRecurringRule, error) {
	row, err := s.GetFinanceRecurringRuleByID(ctx, propertyID, id)
	if err != nil {
		return nil, err
	}
	if title != nil {
		row.Title = *title
	}
	if categoryID != nil {
		row.CategoryID = sql.NullInt64{Int64: *categoryID, Valid: *categoryID > 0}
	}
	if amountCents != nil {
		row.AmountCents = *amountCents
	}
	if direction != nil {
		row.Direction = *direction
	}
	if startMonth != nil {
		row.StartMonth = *startMonth
	}
	if endMonth != nil {
		row.EndMonth = sql.NullString{String: *endMonth, Valid: *endMonth != ""}
	}
	if effectiveFrom != nil {
		row.EffectiveFrom = effectiveFrom.UTC()
	}
	if effectiveTo != nil {
		row.EffectiveTo = sql.NullTime{Time: effectiveTo.UTC(), Valid: true}
	}
	if active != nil {
		row.Active = *active
	}
	now := time.Now().UTC().Format(time.RFC3339)
	activeInt := 0
	if row.Active {
		activeInt = 1
	}
	var effTo interface{}
	if row.EffectiveTo.Valid {
		effTo = row.EffectiveTo.Time.UTC().Format(time.RFC3339)
	}
	_, err = s.DB.ExecContext(ctx, `
		UPDATE finance_recurring_rules
		SET title = ?, category_id = ?, amount_cents = ?, direction = ?, start_month = ?, end_month = ?,
			effective_from = ?, effective_to = ?, active = ?, updated_at = ?
		WHERE id = ? AND property_id = ?`,
		row.Title, nullInt64Value(row.CategoryID), row.AmountCents, row.Direction, row.StartMonth, nullStringValue(row.EndMonth),
		row.EffectiveFrom.UTC().Format(time.RFC3339), effTo, activeInt, now, id, propertyID)
	if err != nil {
		return nil, err
	}
	return s.GetFinanceRecurringRuleByID(ctx, propertyID, id)
}

func (s *Store) OpenFinanceMonth(ctx context.Context, propertyID int64, month string, openedBy *int64, loc *time.Location) (int, error) {
	year, m, err := parseMonthYYYYMM(month)
	if err != nil {
		return 0, err
	}
	// Anchor generated monthly transactions at UTC noon to keep the YYYY-MM
	// stable when filtering by stored timestamp prefix.
	monthAnchorUTC := time.Date(year, time.Month(m), 1, 12, 0, 0, 0, time.UTC)
	monthRef := fmt.Sprintf("%04d-%02d", year, m)
	monthStartRFC := monthAnchorUTC.Format(time.RFC3339)

	cleaningSummary, _ := s.ComputeCleaningMonthlySummary(ctx, propertyID, year, m, loc)

	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return 0, err
	}
	defer tx.Rollback()

	now := time.Now().UTC().Format(time.RFC3339)
	var by interface{}
	if openedBy != nil {
		by = *openedBy
	}
	if _, err := tx.ExecContext(ctx, `
		INSERT INTO finance_month_states (property_id, month, opened_at, opened_by)
		VALUES (?, ?, ?, ?)
		ON CONFLICT(property_id, month) DO NOTHING`, propertyID, monthRef, now, by); err != nil {
		return 0, err
	}

	rows, err := tx.QueryContext(ctx, `
		SELECT id, title, category_id, amount_cents, direction
		FROM finance_recurring_rules
		WHERE property_id = ?
		  AND active = 1
		  AND start_month <= ?
		  AND (end_month IS NULL OR end_month = '' OR end_month >= ?)
		  AND substr(effective_from, 1, 7) <= ?
		  AND (effective_to IS NULL OR substr(effective_to, 1, 7) >= ?)`,
		propertyID, monthRef, monthRef, monthRef, monthRef)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	inserted := 0
	for rows.Next() {
		var ruleID int64
		var title, direction string
		var categoryID sql.NullInt64
		var amount int
		if err := rows.Scan(&ruleID, &title, &categoryID, &amount, &direction); err != nil {
			return 0, err
		}
		ruleRef := fmt.Sprintf("%d:%s", ruleID, monthRef)
		var existing int64
		err := tx.QueryRowContext(ctx, `
			SELECT id
			FROM finance_transactions
			WHERE property_id = ?
			  AND source_type = 'recurring_rule'
			  AND source_reference_id = ?
			LIMIT 1`, propertyID, ruleRef).Scan(&existing)
		if err != nil && err != sql.ErrNoRows {
			return 0, err
		}
		if err == nil {
			_, err = tx.ExecContext(ctx, `
				UPDATE finance_transactions
				SET transaction_date = ?, direction = ?, amount_cents = ?, category_id = ?, note = ?, updated_at = ?
				WHERE id = ?`,
				monthStartRFC, direction, amount, nullInt64Value(categoryID), fmt.Sprintf("Recurring: %s (%s)", title, monthRef), now, existing)
			if err != nil {
				return 0, err
			}
			continue
		}
		// Compatibility path for early format where source_reference_id held only rule ID.
		var legacyID int64
		err = tx.QueryRowContext(ctx, `
			SELECT id
			FROM finance_transactions
			WHERE property_id = ?
			  AND source_type = 'recurring_rule'
			  AND source_reference_id = ?
			  AND note LIKE ?
			LIMIT 1`, propertyID, fmt.Sprintf("%d", ruleID), "%("+monthRef+")%").Scan(&legacyID)
		if err != nil && err != sql.ErrNoRows {
			return 0, err
		}
		if err == nil {
			_, err = tx.ExecContext(ctx, `
				UPDATE finance_transactions
				SET source_reference_id = ?, transaction_date = ?, direction = ?, amount_cents = ?, category_id = ?, note = ?, updated_at = ?
				WHERE id = ?`,
				ruleRef, monthStartRFC, direction, amount, nullInt64Value(categoryID), fmt.Sprintf("Recurring: %s (%s)", title, monthRef), now, legacyID)
			if err != nil {
				return 0, err
			}
			continue
		}
		res, err := tx.ExecContext(ctx, `
			INSERT INTO finance_transactions (
				property_id, transaction_date, direction, amount_cents, category_id, note,
				source_type, source_reference_id, is_auto_generated, created_at, updated_at
			) VALUES (?, ?, ?, ?, ?, ?, 'recurring_rule', ?, 1, ?, ?)`,
			propertyID, monthStartRFC, direction, amount, nullInt64Value(categoryID),
			fmt.Sprintf("Recurring: %s (%s)", title, monthRef), ruleRef, now, now)
		if err != nil {
			return 0, err
		}
		aff, _ := res.RowsAffected()
		inserted += int(aff)
	}
	if err := rows.Err(); err != nil {
		return 0, err
	}

	cleaningCategoryID, err := findFinanceCategoryByCodeTx(ctx, tx, propertyID, "cleaning_salary")
	if err != nil {
		return 0, err
	}
	if cleaningSummary != nil && cleaningSummary.FinalSalaryCents > 0 && cleaningCategoryID > 0 {
		var existingID int64
		err := tx.QueryRowContext(ctx, `
			SELECT id
			FROM finance_transactions
			WHERE property_id = ?
			  AND source_type = 'cleaning_salary'
			  AND source_reference_id = ?
			LIMIT 1`, propertyID, monthRef).Scan(&existingID)
		if err != nil && err != sql.ErrNoRows {
			return 0, err
		}
		if err == sql.ErrNoRows {
			_, err = tx.ExecContext(ctx, `
				INSERT INTO finance_transactions (
					property_id, transaction_date, direction, amount_cents, category_id, note,
					source_type, source_reference_id, is_auto_generated, created_at, updated_at
				) VALUES (?, ?, 'outgoing', ?, ?, ?, 'cleaning_salary', ?, 1, ?, ?)`,
				propertyID, monthStartRFC, cleaningSummary.FinalSalaryCents, cleaningCategoryID,
				fmt.Sprintf("Cleaner salary for %s", monthRef), monthRef, now, now)
		} else {
			_, err = tx.ExecContext(ctx, `
				UPDATE finance_transactions
				SET transaction_date = ?, amount_cents = ?, category_id = ?, note = ?, updated_at = ?
				WHERE id = ?`,
				monthStartRFC, cleaningSummary.FinalSalaryCents, cleaningCategoryID, fmt.Sprintf("Cleaner salary for %s", monthRef), now, existingID)
		}
		if err != nil {
			return 0, err
		}
	}
	if err := tx.Commit(); err != nil {
		return 0, err
	}
	return inserted, nil
}

func (s *Store) ComputeFinanceSummary(ctx context.Context, propertyID int64, month string) (*FinanceSummary, error) {
	summary := &FinanceSummary{Month: month, Breakdown: []FinanceCategoryBreakdown{}}

	_ = s.DB.QueryRowContext(ctx, `
		SELECT
			COALESCE(SUM(CASE WHEN direction = 'incoming' THEN amount_cents ELSE 0 END), 0),
			COALESCE(SUM(CASE WHEN direction = 'outgoing' THEN amount_cents ELSE 0 END), 0)
		FROM finance_transactions
		WHERE property_id = ?`, propertyID).
		Scan(&summary.TotalIncomingCents, &summary.TotalOutgoingCents)

	_ = s.DB.QueryRowContext(ctx, `
		SELECT
			COALESCE(SUM(CASE WHEN direction = 'incoming' THEN amount_cents ELSE 0 END), 0),
			COALESCE(SUM(CASE WHEN direction = 'outgoing' THEN amount_cents ELSE 0 END), 0)
		FROM finance_transactions
		WHERE property_id = ? AND substr(transaction_date, 1, 7) = ?`, propertyID, month).
		Scan(&summary.MonthlyIncomingCents, &summary.MonthlyOutgoingCents)
	summary.MonthlyNetCents = summary.MonthlyIncomingCents - summary.MonthlyOutgoingCents

	_ = s.DB.QueryRowContext(ctx, `
		SELECT COALESCE(SUM(ft.amount_cents), 0)
		FROM finance_transactions ft
		INNER JOIN finance_categories fc ON fc.id = ft.category_id
		WHERE ft.property_id = ?
		  AND ft.direction = 'incoming'
		  AND fc.counts_toward_property_income = 1`, propertyID).
		Scan(&summary.PropertyIncomeCents)

	_ = s.DB.QueryRowContext(ctx, `
		SELECT COALESCE(SUM(ft.amount_cents), 0)
		FROM finance_transactions ft
		INNER JOIN finance_categories fc ON fc.id = ft.category_id
		WHERE ft.property_id = ?
		  AND ft.direction = 'incoming'
		  AND fc.counts_toward_property_income = 1
		  AND substr(ft.transaction_date, 1, 7) = ?`, propertyID, month).
		Scan(&summary.MonthlyPropertyIncomeCents)

	_ = s.DB.QueryRowContext(ctx, `
		SELECT COALESCE(SUM(amount_cents), 0)
		FROM finance_transactions
		WHERE property_id = ?
		  AND source_type = 'cleaning_salary'
		  AND source_reference_id = ?`, propertyID, month).
		Scan(&summary.CleanerExpenseCents)

	if summary.MonthlyPropertyIncomeCents > 0 {
		summary.CleanerMargin = float64(summary.CleanerExpenseCents) / float64(summary.MonthlyPropertyIncomeCents)
	}

	rows, err := s.DB.QueryContext(ctx, `
		SELECT ft.category_id, fc.code, fc.title,
			COALESCE(SUM(CASE WHEN ft.direction = 'incoming' THEN ft.amount_cents ELSE 0 END), 0) AS incoming_cents,
			COALESCE(SUM(CASE WHEN ft.direction = 'outgoing' THEN ft.amount_cents ELSE 0 END), 0) AS outgoing_cents
		FROM finance_transactions ft
		LEFT JOIN finance_categories fc ON fc.id = ft.category_id
		WHERE ft.property_id = ? AND substr(ft.transaction_date, 1, 7) = ?
		GROUP BY ft.category_id, fc.code, fc.title
		ORDER BY outgoing_cents DESC, incoming_cents DESC`, propertyID, month)
	if err != nil {
		return summary, nil
	}
	defer rows.Close()
	for rows.Next() {
		var r FinanceCategoryBreakdown
		if err := rows.Scan(&r.CategoryID, &r.CategoryCode, &r.CategoryTitle, &r.IncomingCents, &r.OutgoingCents); err != nil {
			return summary, nil
		}
		summary.Breakdown = append(summary.Breakdown, r)
	}
	return summary, nil
}

func findFinanceCategoryByCodeTx(ctx context.Context, tx *sql.Tx, propertyID int64, code string) (int64, error) {
	var id int64
	err := tx.QueryRowContext(ctx, `
		SELECT id
		FROM finance_categories
		WHERE active = 1
		  AND code = ?
		  AND (property_id IS NULL OR property_id = ?)
		ORDER BY CASE WHEN property_id IS NULL THEN 1 ELSE 0 END
		LIMIT 1`, code, propertyID).Scan(&id)
	if err == sql.ErrNoRows {
		return 0, nil
	}
	return id, err
}

func parseMonthYYYYMM(month string) (int, int, error) {
	var y, m int
	if _, err := fmt.Sscanf(month, "%d-%d", &y, &m); err != nil {
		return 0, 0, fmt.Errorf("month must be YYYY-MM")
	}
	if y < 2000 || y > 3000 || m < 1 || m > 12 {
		return 0, 0, fmt.Errorf("month must be YYYY-MM")
	}
	return y, m, nil
}

func nullStringValue(v sql.NullString) interface{} {
	if !v.Valid {
		return nil
	}
	return v.String
}

func nullInt64Value(v sql.NullInt64) interface{} {
	if !v.Valid {
		return nil
	}
	return v.Int64
}

func scanFinanceTransactionsRows(rows *sql.Rows) ([]FinanceTransaction, error) {
	out := make([]FinanceTransaction, 0)
	for rows.Next() {
		var r FinanceTransaction
		var txDate, created, updated string
		var auto, income, mapped int
		if err := rows.Scan(&r.ID, &r.PropertyID, &txDate, &r.Direction, &r.AmountCents, &r.CategoryID,
			&r.Note, &r.SourceType, &r.SourceReference, &auto, &r.AttachmentPath, &created, &updated,
			&r.CategoryCode, &r.CategoryTitle, &income, &mapped); err != nil {
			return nil, err
		}
		r.TransactionDate, _ = time.Parse(time.RFC3339, txDate)
		r.CreatedAt, _ = time.Parse(time.RFC3339, created)
		r.UpdatedAt, _ = time.Parse(time.RFC3339, updated)
		r.IsAutoGenerated = auto == 1
		r.CountsTowardIncome = income == 1
		r.MappedToStay = mapped == 1
		out = append(out, r)
	}
	return out, rows.Err()
}
