package store

import (
	"context"
	"testing"
	"time"

	"pms/backend/internal/testutil"
)

func TestSyncFinanceGeneratedEntries_CreatesAndUpdatesCleaningExpense(t *testing.T) {
	st := &Store{DB: testutil.OpenTestDB(t)}
	pid := setupFinanceProperty(t, st)
	ctx := context.Background()
	const month = "2026-08"
	if _, err := st.CreateFinanceRecurringRule(ctx, &FinanceRecurringRule{
		PropertyID: pid, Title: "Internet", AmountCents: 2500,
		Direction: "outgoing", Frequency: "monthly", StartMonth: month,
		EffectiveFrom: time.Date(2026, 8, 1, 0, 0, 0, 0, time.UTC), Active: true,
	}); err != nil {
		t.Fatal(err)
	}
	if err := st.CreateCleaningAdjustment(ctx, pid, 2026, 8, 10000, "Salary", nil); err != nil {
		t.Fatal(err)
	}

	var cleaningID int64
	for i, salary := range []int{10000, 12000, 12000} {
		if i == 1 {
			if err := st.CreateCleaningAdjustment(ctx, pid, 2026, 8, 2000, "Bonus", nil); err != nil {
				t.Fatal(err)
			}
		}
		sync, changes, err := st.SyncFinanceGeneratedEntriesForMonth(ctx, pid, month, nil, time.UTC, "manual")
		if err != nil {
			t.Fatalf("sync %d: %v", i, err)
		}
		if sync.Status != "synced" || !sync.LastSyncedAt.Valid {
			t.Fatalf("sync metadata: %+v", sync)
		}
		if i == 0 {
			if changes.CleaningSalaryInserted != 1 || changes.RecurringInserted != 1 {
				t.Fatalf("initial changes: %+v", changes)
			}
		} else if changes.CleaningSalaryInserted != 0 || changes.CleaningSalaryUpdated != 1 || changes.RecurringInserted != 0 {
			t.Fatalf("repeat changes: %+v", changes)
		}
		txs, err := st.ListFinanceTransactions(ctx, pid, month, 0, 0)
		if err != nil {
			t.Fatal(err)
		}
		if len(txs) != 2 {
			t.Fatalf("got %d transactions, want cleaning and recurring expenses", len(txs))
		}
		for _, tx := range txs {
			if tx.SourceType == "cleaning_salary" {
				if tx.AmountCents != salary || tx.Direction != "outgoing" || !tx.IsAutoGenerated || tx.SourceReference.String != month {
					t.Fatalf("cleaning expense: %+v", tx)
				}
				if i == 0 {
					cleaningID = tx.ID
				} else if tx.ID != cleaningID {
					t.Fatalf("cleaning expense was replaced: %d -> %d", cleaningID, tx.ID)
				}
			}
		}
		summary, err := st.ComputeFinanceSummary(ctx, pid, month)
		if err != nil {
			t.Fatal(err)
		}
		if summary.MonthlyOutgoingCents != salary+2500 || summary.CleanerExpenseCents != salary {
			t.Fatalf("unexpected outgoing totals: %+v", summary)
		}
	}
}
