package store

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"pms/backend/internal/testutil"
)

// TestImportBookingPayoutRow_AtomicOnFailure verifies that when the payout
// insert fails (here forced by a duplicate reference number via a unique
// index violation), the sibling finance transaction created in the same
// transaction is rolled back. This is the core reliability contract of the
// Phase B M2 hardening work.
func TestImportBookingPayoutRow_AtomicOnFailure(t *testing.T) {
	st := &Store{DB: testutil.OpenTestDB(t)}
	ctx := context.Background()
	pid := setupFinanceProperty(t, st)
	catID := categoryIDByCode(t, st, pid, "booking_income")

	// Seed a first payout row so a second insert with the same reference fails.
	firstTx := &FinanceTransaction{
		PropertyID:      pid,
		TransactionDate: time.Now().UTC(),
		Direction:       "incoming",
		AmountCents:     1000,
		CategoryID:      sql.NullInt64{Int64: catID, Valid: true},
		SourceType:      "booking_payout",
		SourceReference: sql.NullString{String: "REF-1", Valid: true},
		IsAutoGenerated: true,
	}
	first := &FinanceBookingPayout{
		PropertyID:      pid,
		ReferenceNumber: "REF-1",
		NetCents:        1000,
		PayoutDate:      time.Now().UTC(),
	}
	if _, err := st.ImportBookingPayoutRow(ctx, firstTx, first, 0); err != nil {
		t.Fatalf("seed import: %v", err)
	}
	baseTxCount := countFinanceTransactions(t, st, pid)
	basePayoutCount := countBookingPayouts(t, st, pid)

	// Second import with the same reference must fail wholesale.
	dupTx := &FinanceTransaction{
		PropertyID:      pid,
		TransactionDate: time.Now().UTC(),
		Direction:       "incoming",
		AmountCents:     2000,
		CategoryID:      sql.NullInt64{Int64: catID, Valid: true},
		SourceType:      "booking_payout",
		SourceReference: sql.NullString{String: "REF-1", Valid: true},
		IsAutoGenerated: true,
	}
	dupPayout := &FinanceBookingPayout{
		PropertyID:      pid,
		ReferenceNumber: "REF-1",
		NetCents:        2000,
		PayoutDate:      time.Now().UTC(),
	}
	if _, err := st.ImportBookingPayoutRow(ctx, dupTx, dupPayout, 0); err == nil {
		t.Fatal("expected duplicate import to fail")
	}

	// No orphan finance transaction must remain from the failed import.
	if got := countFinanceTransactions(t, st, pid); got != baseTxCount {
		t.Fatalf("finance_transactions count changed after failed import: want %d got %d", baseTxCount, got)
	}
	if got := countBookingPayouts(t, st, pid); got != basePayoutCount {
		t.Fatalf("finance_booking_payouts count changed after failed import: want %d got %d", basePayoutCount, got)
	}
}

func TestImportBookingPayoutRow_ReusesExistingTransaction(t *testing.T) {
	st := &Store{DB: testutil.OpenTestDB(t)}
	ctx := context.Background()
	pid := setupFinanceProperty(t, st)
	catID := categoryIDByCode(t, st, pid, "booking_income")

	// Create a standalone transaction first, then import the payout only.
	created, err := st.CreateFinanceTransaction(ctx, &FinanceTransaction{
		PropertyID:      pid,
		TransactionDate: time.Now().UTC(),
		Direction:       "incoming",
		AmountCents:     3000,
		CategoryID:      sql.NullInt64{Int64: catID, Valid: true},
		SourceType:      "booking_payout",
		SourceReference: sql.NullString{String: "REF-42", Valid: true},
		IsAutoGenerated: true,
	})
	if err != nil {
		t.Fatalf("seed tx: %v", err)
	}
	baseTxCount := countFinanceTransactions(t, st, pid)

	payout := &FinanceBookingPayout{
		PropertyID:      pid,
		ReferenceNumber: "REF-42",
		NetCents:        3000,
		PayoutDate:      time.Now().UTC(),
	}
	txID, err := st.ImportBookingPayoutRow(ctx, nil, payout, created.ID)
	if err != nil {
		t.Fatalf("import with existing tx: %v", err)
	}
	if txID != created.ID {
		t.Fatalf("expected reused tx id %d, got %d", created.ID, txID)
	}
	if got := countFinanceTransactions(t, st, pid); got != baseTxCount {
		t.Fatalf("no new transaction expected: want %d got %d", baseTxCount, got)
	}
}

func TestTryAcquireJobLease_ExclusiveBetweenOwners(t *testing.T) {
	st := &Store{DB: testutil.OpenTestDB(t)}
	ctx := context.Background()

	ok, err := st.TryAcquireJobLease(ctx, "occupancy_sync", "owner-a", time.Minute)
	if err != nil || !ok {
		t.Fatalf("owner-a first acquire: ok=%v err=%v", ok, err)
	}

	ok, err = st.TryAcquireJobLease(ctx, "occupancy_sync", "owner-b", time.Minute)
	if err != nil {
		t.Fatalf("owner-b contested acquire error: %v", err)
	}
	if ok {
		t.Fatal("owner-b must not acquire a live lease held by owner-a")
	}

	// Renewal by the current owner should succeed.
	ok, err = st.TryAcquireJobLease(ctx, "occupancy_sync", "owner-a", time.Minute)
	if err != nil || !ok {
		t.Fatalf("owner-a renewal: ok=%v err=%v", ok, err)
	}

	// Release + takeover path.
	if err := st.ReleaseJobLease(ctx, "occupancy_sync", "owner-a"); err != nil {
		t.Fatalf("release: %v", err)
	}
	ok, err = st.TryAcquireJobLease(ctx, "occupancy_sync", "owner-b", time.Minute)
	if err != nil || !ok {
		t.Fatalf("owner-b post-release acquire: ok=%v err=%v", ok, err)
	}
}

func TestTryAcquireJobLease_ExpiredLeaseCanBeTakenOver(t *testing.T) {
	st := &Store{DB: testutil.OpenTestDB(t)}
	ctx := context.Background()

	// Acquire with a very small TTL and then manually age the row so the
	// takeover WHERE clause sees the lease as expired.
	if _, err := st.TryAcquireJobLease(ctx, "nuki_cleanup", "owner-old", time.Minute); err != nil {
		t.Fatalf("acquire: %v", err)
	}
	past := time.Now().UTC().Add(-time.Hour).Format(time.RFC3339)
	if _, err := st.DB.ExecContext(ctx, `UPDATE job_leases SET expires_at = ? WHERE job_name = ?`, past, "nuki_cleanup"); err != nil {
		t.Fatalf("age lease: %v", err)
	}

	ok, err := st.TryAcquireJobLease(ctx, "nuki_cleanup", "owner-new", time.Minute)
	if err != nil || !ok {
		t.Fatalf("takeover of expired lease: ok=%v err=%v", ok, err)
	}
}

func countFinanceTransactions(t *testing.T, st *Store, pid int64) int {
	t.Helper()
	var n int
	if err := st.DB.QueryRowContext(context.Background(), `SELECT COUNT(*) FROM finance_transactions WHERE property_id = ?`, pid).Scan(&n); err != nil {
		t.Fatalf("count finance_transactions: %v", err)
	}
	return n
}

func countBookingPayouts(t *testing.T, st *Store, pid int64) int {
	t.Helper()
	var n int
	if err := st.DB.QueryRowContext(context.Background(), `SELECT COUNT(*) FROM finance_booking_payouts WHERE property_id = ?`, pid).Scan(&n); err != nil {
		t.Fatalf("count finance_booking_payouts: %v", err)
	}
	return n
}
